"""
HIS Add-on Orchestrator
=======================
Public orchestrator — no HIS source code here, no hardcoded repo URL.

The wizard collects:
  1. HIS repo URL + optional GitHub token  (validated before proceeding)
  2. LLM provider + API key
  3. Telegram bot token + user ID           (optional)
  4. Public URL                             (optional, needed for Telegram)

HA URL and access token are auto-provisioned from the Supervisor API.

Routes:
  GET  /                       → wizard HTML
  GET  /prefill                → pre-filled values (Supervisor + existing config)
  POST /validate-repo          → test git clone access
  POST /configure              → write /share/his/his/.env
  GET  /deploy                 → SSE: git clone → compose up → migrations
  GET  /providers/{p}/models   → live model list from provider API
  POST /validate-domain        → test public URL reachability
  GET  /uninstall              → SSE: compose down -v → rm -rf /share/his
  GET  /health                 → {"status":"ok"}
"""

from __future__ import annotations

import json
import logging
import os
import pathlib
import re
import secrets
import shutil
import ssl
import subprocess
import threading
import time
import urllib.request
from typing import Any

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, StreamingResponse

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title="HIS Orchestrator", docs_url=None, redoc_url=None)

# ── Paths ──────────────────────────────────────────────────────────────────────

HIS_DIR       = pathlib.Path("/share/his")
REPO_DIR      = HIS_DIR / "repo"                 # git clone target
STACK_DIR     = REPO_DIR                         # docker-compose.yml is at repo root
ENV_FILE      = STACK_DIR / ".env"
ENV_STAGING   = HIS_DIR / ".env.staging"         # written pre-clone, moved into repo after
CONFIG_FILE   = HIS_DIR / "orchestrator.json"    # persists repo_url + token
COMPOSE_FILE  = STACK_DIR / "docker-compose.yml"
COMPOSE_ADDON = STACK_DIR / "ha-addon" / "docker-compose.addon.yml"
READY_FLAG    = pathlib.Path("/tmp/his_stack_ready")

# ── Supervisor cache ───────────────────────────────────────────────────────────

_supervisor_ha_token: str = ""
_supervisor_ha_url: str = ""
SUPERVISOR_TOKEN = os.environ.get("SUPERVISOR_TOKEN", "")
SUPERVISOR_API   = "http://supervisor"


def _supervisor_get(path: str) -> dict:
    req = urllib.request.Request(
        f"{SUPERVISOR_API}{path}",
        headers={"Authorization": f"Bearer {SUPERVISOR_TOKEN}"},
    )
    with urllib.request.urlopen(req, timeout=8) as resp:
        return json.loads(resp.read())


def _ha_internal_url() -> str:
    try:
        data = _supervisor_get("/core/info")
        return data.get("data", {}).get("homeassistant_url") or "http://homeassistant.local:8123"
    except Exception:
        return "http://homeassistant.local:8123"


def _create_ha_token(name: str = "HIS") -> str:
    try:
        payload = json.dumps({"name": name}).encode()
        req = urllib.request.Request(
            f"{SUPERVISOR_API}/core/api/auth/long_lived_access_token",
            data=payload,
            headers={
                "Authorization": f"Bearer {SUPERVISOR_TOKEN}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read()).get("token", "")
    except Exception as exc:
        logger.warning("Could not auto-create HA token: %s", exc)
        return ""


def _init_supervisor_cache() -> None:
    global _supervisor_ha_token, _supervisor_ha_url
    _supervisor_ha_url = _ha_internal_url()
    existing = _read_env()
    _supervisor_ha_token = existing.get("HA_TOKEN") or _create_ha_token("HIS")
    logger.info("Supervisor: HA URL=%s token=%s", _supervisor_ha_url,
                "ok" if _supervisor_ha_token else "FAILED")


@app.on_event("startup")
async def _startup():
    import asyncio
    asyncio.get_event_loop().run_in_executor(None, _init_supervisor_cache)


# ── Orchestrator config (repo URL + token) ────────────────────────────────────

def _read_orconfig() -> dict:
    if CONFIG_FILE.exists():
        try:
            return json.loads(CONFIG_FILE.read_text())
        except Exception:
            pass
    return {}


def _write_orconfig(data: dict) -> None:
    HIS_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(data))


# ── .env helpers ───────────────────────────────────────────────────────────────

ENV_TEMPLATE = """\
# Generated by HIS Add-on Setup Wizard
LLM_PRIMARY_PROVIDER={llm_primary_provider}
EMBEDDING_PROVIDER={embedding_provider}

GEMINI_API_KEY={gemini_api_key}
GEMINI_MODEL={gemini_model}
GEMINI_EMBEDDING_MODEL=text-embedding-004

GROQ_API_KEY={groq_api_key}
GROQ_MODEL={groq_model}

OPENROUTER_API_KEY={openrouter_api_key}
OPENROUTER_MODEL={openrouter_model}

OLLAMA_BASE_URL={ollama_base_url}
OLLAMA_MODEL={ollama_model}

HA_URL={ha_url}
HA_TOKEN={ha_token}

TELEGRAM_BOT_TOKEN={telegram_bot_token}
TELEGRAM_WEBHOOK_SECRET={telegram_webhook_secret}
TELEGRAM_ALLOWED_USER_IDS={telegram_allowed_user_ids}

HIS_API_TOKEN={his_api_token}
PUBLIC_BASE_URL={public_base_url}
HIS_PATH_PREFIX=/his

POSTGRES_PASSWORD={postgres_password}
POSTGRES_URL=postgresql+asyncpg://his:{postgres_password}@his_postgres:5432/his
POSTGRES_URL_SYNC=postgresql+psycopg2://his:{postgres_password}@his_postgres:5432/his

ENV=production
LOG_LEVEL=INFO
GATEWAY_HOST=0.0.0.0
GATEWAY_PORT=8000
"""


def _read_env() -> dict[str, str]:
    path = ENV_FILE if ENV_FILE.exists() else (ENV_STAGING if ENV_STAGING.exists() else None)
    if not path:
        return {}
    result: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            result[k.strip()] = v.strip()
    return result


def _write_env(fields: dict[str, str]) -> None:
    HIS_DIR.mkdir(parents=True, exist_ok=True)
    # Write to staging path — _ensure_repo moves it into REPO_DIR after clone
    ENV_STAGING.write_text(ENV_TEMPLATE.format(**fields))


# ── Git helpers ────────────────────────────────────────────────────────────────

def _git_url_with_token(url: str, token: str) -> str:
    """Inject token into https URL: https://TOKEN@github.com/..."""
    if token and url.startswith("https://"):
        return url.replace("https://", f"https://{token}@", 1)
    return url


def _validate_repo(url: str, token: str) -> tuple[bool, str]:
    """Try a shallow ls-remote to check access. Returns (ok, message)."""
    auth_url = _git_url_with_token(url, token)
    result = subprocess.run(
        ["git", "ls-remote", "--heads", auth_url],
        capture_output=True, text=True, timeout=15,
    )
    if result.returncode == 0:
        return True, "Repository accessible."
    err = result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "unknown error"
    return False, err


def _ensure_repo(url: str, token: str, log_fn) -> bool:
    auth_url = _git_url_with_token(url, token)
    if not COMPOSE_FILE.exists():
        # Remove empty dir if pre-created
        if REPO_DIR.exists() and not any(REPO_DIR.iterdir()):
            REPO_DIR.rmdir()
        log_fn("→ Cloning HIS repository…")
        r = subprocess.run(
            ["git", "clone", "--depth=1", auth_url, str(REPO_DIR)],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            log_fn(f"✗ git clone failed: {r.stderr.strip().splitlines()[-1]}")
            return False
        log_fn("✓ Repository cloned.")
    else:
        log_fn("→ Pulling latest…")
        subprocess.run(
            ["git", "-C", str(REPO_DIR), "remote", "set-url", "origin", auth_url],
            capture_output=True,
        )
        subprocess.run(
            ["git", "-C", str(REPO_DIR), "pull", "--ff-only"],
            capture_output=True,
        )
        log_fn("✓ Up to date.")
    # Move staging .env into STACK_DIR now that repo is cloned
    if ENV_STAGING.exists():
        STACK_DIR.mkdir(parents=True, exist_ok=True)
        ENV_STAGING.rename(ENV_FILE)
    return True


def _run_compose(log_fn) -> bool:
    ansi = re.compile(r"\x1b\[[0-9;]*m")
    proc = subprocess.Popen(
        ["docker", "compose",
         "-f", str(COMPOSE_FILE), "-f", str(COMPOSE_ADDON),
         "--env-file", str(ENV_FILE),
         "up", "-d", "--remove-orphans"],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, cwd=str(STACK_DIR),
    )
    for line in proc.stdout:
        clean = ansi.sub("", line).rstrip()
        if clean:
            log_fn(clean)
    proc.wait()
    if proc.returncode != 0:
        log_fn(f"✗ docker compose exited with code {proc.returncode}")
        return False

    log_fn("→ Running database migrations…")
    mig = subprocess.run([
        "docker", "compose",
        "-f", str(COMPOSE_FILE), "--env-file", str(ENV_FILE),
        "run", "--rm",
        "-e", "PYTHONPATH=/app:/app/shared_lib:/app/knowledge_lib",
        "--entrypoint", "", "gateway",
        "sh", "-c", "cd /app/knowledge_lib && alembic upgrade head",
    ], capture_output=True, text=True, cwd=str(STACK_DIR))
    for line in (mig.stdout + mig.stderr).splitlines():
        if line.strip():
            log_fn(line)
    log_fn("✓ Migrations applied." if mig.returncode == 0
           else "⚠ Migrations failed — stack running but DB may be incomplete.")

    log_fn("→ Connecting add-on to HIS network…")
    hostname = os.environ.get("HOSTNAME", "")
    if hostname:
        r = subprocess.run(["docker", "network", "connect", "his_his_net", hostname],
                           capture_output=True, text=True)
        log_fn("✓ Joined his_his_net." if r.returncode == 0
               else f"  (network: {r.stderr.strip() or 'already connected'})")
    return True


# ── Compose helpers ────────────────────────────────────────────────────────────

def _run_compose(log_fn) -> bool:
    ansi = re.compile(r"\x1b\[[0-9;]*m")
    proc = subprocess.Popen(
        ["docker", "compose",
         "-f", str(COMPOSE_FILE), "-f", str(COMPOSE_ADDON),
         "--env-file", str(ENV_FILE),
         "up", "-d", "--remove-orphans"],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, cwd=str(STACK_DIR),
    )
    for line in proc.stdout:
        clean = ansi.sub("", line).rstrip()
        if clean:
            log_fn(clean)
    proc.wait()
    if proc.returncode != 0:
        log_fn(f"✗ docker compose exited with code {proc.returncode}")
        return False

    log_fn("→ Running database migrations…")
    mig = subprocess.run([
        "docker", "compose",
        "-f", str(COMPOSE_FILE), "--env-file", str(ENV_FILE),
        "run", "--rm",
        "-e", "PYTHONPATH=/app:/app/shared_lib:/app/knowledge_lib",
        "--entrypoint", "", "gateway",
        "sh", "-c", "cd /app/knowledge_lib && alembic upgrade head",
    ], capture_output=True, text=True, cwd=str(STACK_DIR))
    for line in (mig.stdout + mig.stderr).splitlines():
        if line.strip():
            log_fn(line)
    log_fn("✓ Migrations applied." if mig.returncode == 0
           else "⚠ Migrations failed — stack running but DB may be incomplete.")

    log_fn("→ Connecting add-on to HIS network…")
    hostname = os.environ.get("HOSTNAME", "")
    if hostname:
        r = subprocess.run(["docker", "network", "connect", "his_his_net", hostname],
                           capture_output=True, text=True)
        log_fn("✓ Joined his_his_net." if r.returncode == 0
               else f"  (network: {r.stderr.strip() or 'already connected'})")
    return True


# ── Model list ─────────────────────────────────────────────────────────────────

_MODEL_CACHE: dict[tuple, tuple[float, list]] = {}
_MODEL_TTL = 300


def _fetch_models(provider: str, api_key: str | None) -> list[dict]:
    def _get(url: str, headers: dict) -> dict:
        req = urllib.request.Request(url, headers=headers)
        ctx = ssl.create_default_context() if url.startswith("https") else None
        with urllib.request.urlopen(req, timeout=12, **({"context": ctx} if ctx else {})) as r:
            return json.loads(r.read())

    def _pretty(mid: str) -> str:
        return mid.split("/")[-1].split(":")[0].replace("-", " ").replace("_", " ").title()

    if provider == "groq":
        data = _get("https://api.groq.com/openai/v1/models",
                    {"Authorization": f"Bearer {api_key or ''}", "User-Agent": "HIS/1.0"})
        rec = {"llama-3.3-70b-versatile", "meta-llama/llama-4-scout-17b-16e-instruct", "llama-3.1-8b-instant"}
        return sorted([
            {"id": m["id"], "name": _pretty(m["id"]), "context_length": m.get("context_window", 0),
             "supports_tools": True, "recommended": m["id"] in rec, "tags": ["chat"]}
            for m in data.get("data", [])
            if not any(k in m["id"].lower() for k in ("whisper", "guard", "tts"))
        ], key=lambda x: (not x["recommended"], -(x["context_length"] or 0)))

    if provider == "openrouter":
        data = _get("https://openrouter.ai/api/v1/models",
                    {"Authorization": f"Bearer {api_key or ''}", "HTTP-Referer": "https://his.local",
                     "X-Title": "HIS", "User-Agent": "HIS/1.0"})
        return sorted([
            {"id": m["id"], "name": m.get("name") or _pretty(m["id"]),
             "context_length": m.get("context_length", 0), "supports_tools": True,
             "recommended": any(k in m["id"].lower() for k in ("deepseek", "gemma", "qwen")),
             "tags": ["free"]}
            for m in data.get("data", [])
            if str(m.get("pricing", {}).get("prompt", "1")) in ("0", "0.0", "0.00")
        ], key=lambda x: (not x["recommended"], -(x["context_length"] or 0)))

    if provider == "ollama":
        base = (api_key or "http://ollama:11434").rstrip("/")
        data = _get(f"{base}/api/tags", {"User-Agent": "HIS/1.0"})
        return [
            {"id": m.get("name", ""), "name": _pretty(m.get("name", "")),
             "context_length": 0, "supports_tools": True,
             "recommended": any(k in m.get("name", "").lower() for k in ("llama3", "qwen", "mistral")),
             "tags": ["local"]}
            for m in data.get("models", [])
            if "embed" not in m.get("name", "").lower()
        ]

    if provider == "gemini":
        data = _get(
            f"https://generativelanguage.googleapis.com/v1beta/models?key={api_key or ''}",
            {"User-Agent": "HIS/1.0"},
        )
        rec = {"gemini-2.0-flash", "gemini-2.5-flash", "gemini-3.5-flash"}
        return sorted([
            {"id": m["name"].removeprefix("models/"), "name": m.get("displayName", m["name"]),
             "context_length": m.get("inputTokenLimit", 0), "supports_tools": True,
             "recommended": m["name"].removeprefix("models/") in rec, "tags": ["chat"]}
            for m in data.get("models", [])
            if "embedding" not in m["name"].lower()
            and "generateContent" in m.get("supportedGenerationMethods", [])
        ], key=lambda x: (not x["recommended"], -(x["context_length"] or 0)))

    return []


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok", "mode": "wizard"}


@app.get("/prefill")
async def prefill():
    env = _read_env()
    orc = _read_orconfig()
    result = {k: v for k, v in env.items() if v not in ("...", "")}
    if not result.get("HA_URL") and _supervisor_ha_url:
        result["HA_URL"] = _supervisor_ha_url
    if not result.get("HA_TOKEN") and _supervisor_ha_token:
        result["HA_TOKEN"] = _supervisor_ha_token
    if orc.get("repo_url"):
        result["REPO_URL"] = orc["repo_url"]
    if orc.get("repo_token"):
        result["REPO_TOKEN"] = orc["repo_token"]
    keys = [
        "REPO_URL", "REPO_TOKEN",
        "GEMINI_API_KEY", "GEMINI_MODEL", "GROQ_API_KEY", "GROQ_MODEL",
        "OPENROUTER_API_KEY", "OPENROUTER_MODEL", "OLLAMA_BASE_URL", "OLLAMA_MODEL",
        "LLM_PRIMARY_PROVIDER", "HA_URL", "HA_TOKEN", "TELEGRAM_BOT_TOKEN",
        "TELEGRAM_WEBHOOK_SECRET", "TELEGRAM_ALLOWED_USER_IDS", "HIS_API_TOKEN",
        "PUBLIC_BASE_URL", "POSTGRES_PASSWORD",
    ]
    return {k: result[k] for k in keys if k in result}


@app.post("/validate-repo")
async def validate_repo(request: Request):
    body = await request.json()
    url   = body.get("url", "").strip()
    token = body.get("token", "").strip()
    if not url:
        return {"ok": False, "error": "Repository URL is required."}
    import asyncio
    try:
        ok, msg = await asyncio.to_thread(_validate_repo, url, token)
        return {"ok": ok, "message": msg}
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "Timed out — check the URL and your network."}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


@app.post("/configure")
async def configure(request: Request):
    fields: dict[str, str] = await request.json()

    repo_url   = fields.pop("repo_url", "").strip()
    repo_token = fields.pop("repo_token", "").strip()
    if not repo_url:
        return {"ok": False, "error": "Repository URL is required."}

    has_ai = (
        fields.get("gemini_api_key", "").strip()
        or fields.get("groq_api_key", "").strip()
        or fields.get("openrouter_api_key", "").strip()
        or fields.get("llm_primary_provider") == "ollama"
    )
    if not has_ai:
        return {"ok": False, "error": "At least one AI provider is required."}

    if fields.get("ha_token") == "__from_prefill__":
        fields["ha_token"] = _supervisor_ha_token
    if not fields.get("ha_url") or fields.get("ha_url") == "__from_prefill__":
        fields["ha_url"] = _supervisor_ha_url or "http://homeassistant.local:8123"
    if not fields.get("ha_token", "").strip():
        return {"ok": False, "error": "Home Assistant token could not be auto-provisioned. Please enter it manually in the HA section."}

    fields.setdefault("llm_primary_provider", "gemini")
    fields.setdefault("embedding_provider", "gemini")
    fields.setdefault("gemini_model", "gemini-2.5-flash")
    fields.setdefault("groq_api_key", "")
    fields.setdefault("groq_model", "llama-3.3-70b-versatile")
    fields.setdefault("openrouter_api_key", "")
    fields.setdefault("openrouter_model", "deepseek/deepseek-v4-flash:free")
    fields.setdefault("ollama_base_url", "http://ollama:11434")
    fields.setdefault("ollama_model", "llama3.2:3b")
    fields.setdefault("ha_url", "http://homeassistant.local:8123")
    fields.setdefault("public_base_url", "")
    fields.setdefault("telegram_bot_token", "")
    fields.setdefault("telegram_webhook_secret", secrets.token_hex(16))
    fields.setdefault("telegram_allowed_user_ids", "[]")
    fields.setdefault("his_api_token", secrets.token_hex(32))
    fields.setdefault("postgres_password", secrets.token_hex(16))

    try:
        _write_orconfig({"repo_url": repo_url, "repo_token": repo_token})
        _write_env(fields)
        return {"ok": True}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


_deploy_lock = threading.Lock()
_deploy_in_progress = False


@app.get("/deploy")
async def deploy():
    global _deploy_in_progress
    with _deploy_lock:
        if _deploy_in_progress:
            raise HTTPException(409, "Deploy already in progress")
        _deploy_in_progress = True

    async def stream():
        global _deploy_in_progress
        lines: list[str] = []
        def log(msg): lines.append(msg)

        def flush():
            nonlocal lines
            out, lines = lines, []
            return out

        try:
            yield "data: ╔══════════════════════════════════╗\n\n"
            yield "data: ║     HIS — First-run Bootstrap    ║\n\n"
            yield "data: ╚══════════════════════════════════╝\n\n"

            orc = _read_orconfig()
            if not _ensure_repo(orc.get("repo_url", ""), orc.get("repo_token", ""), log):
                for l in flush(): yield f"data: {l}\n\n"
                yield "event: error\ndata: \n\n"
                return
            for l in flush(): yield f"data: {l}\n\n"

            if not _run_compose(log):
                for l in flush(): yield f"data: {l}\n\n"
                yield "event: error\ndata: \n\n"
                return
            for l in flush(): yield f"data: {l}\n\n"

            yield "data: ✅ HIS is running!\n\n"
            READY_FLAG.touch()
            yield "event: done\ndata: \n\n"

        except Exception as exc:
            yield f"data: ERROR: {exc}\n\n"
            yield "event: error\ndata: \n\n"
        finally:
            with _deploy_lock:
                _deploy_in_progress = False

    return StreamingResponse(stream(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@app.get("/providers/{provider}/models")
async def list_models(provider: str, api_key: str | None = Query(default=None)):
    if provider not in {"gemini", "groq", "openrouter", "ollama"}:
        raise HTTPException(400, f"Unknown provider '{provider}'")
    cache_key = (provider, (api_key or "")[:6])
    cached = _MODEL_CACHE.get(cache_key)
    if cached and time.monotonic() - cached[0] < _MODEL_TTL:
        return {"provider": provider, "models": cached[1], "count": len(cached[1])}
    import asyncio
    try:
        models = await asyncio.to_thread(_fetch_models, provider, api_key)
    except Exception as exc:
        msg = str(exc)
        code = 401 if any(k in msg for k in ("401", "403", "Invalid API", "Unauthorized")) else 502
        raise HTTPException(code, msg)
    _MODEL_CACHE[cache_key] = (time.monotonic(), models)
    return {"provider": provider, "models": models, "count": len(models)}


@app.post("/validate-domain")
async def validate_domain(request: Request):
    body = await request.json()
    url = str(body.get("url", "")).rstrip("/")
    if not url.startswith(("http://", "https://")):
        return {"ok": False, "error": "URL must start with http:// or https://"}
    try:
        ctx = ssl.create_default_context()
        req = urllib.request.Request(url, headers={"User-Agent": "HIS/1.0"})
        with urllib.request.urlopen(req, timeout=6, context=ctx) as resp:
            return {"ok": resp.status < 500, "note": f"HTTP {resp.status}"}
    except Exception as exc:
        msg = str(exc)
        if "Name or service not known" in msg or "nodename nor servname" in msg:
            msg = "Domain not found"
        elif "timed out" in msg.lower():
            msg = "Connection timed out"
        elif "SSL" in msg or "certificate" in msg.lower():
            msg = "SSL error — check your HTTPS certificate"
        return {"ok": False, "error": msg}


@app.get("/uninstall")
async def uninstall():
    async def stream():
        ansi = re.compile(r"\x1b\[[0-9;]*m")
        def run(cmd, **kw):
            p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, **kw)
            lines = [ansi.sub("", l).rstrip() for l in p.stdout if l.strip()]
            p.wait()
            return p.returncode, lines

        yield "data: ╔══════════════════════════════════╗\n\n"
        yield "data: ║       HIS — Uninstalling…        ║\n\n"
        yield "data: ╚══════════════════════════════════╝\n\n"

        if COMPOSE_FILE.exists() and ENV_FILE.exists():
            yield "data: → Stopping containers and removing volumes…\n\n"
            code, lines = run([
                "docker", "compose",
                "-f", str(COMPOSE_FILE), "-f", str(COMPOSE_ADDON),
                "--env-file", str(ENV_FILE),
                "down", "--volumes", "--remove-orphans", "--timeout", "30",
            ], cwd=str(STACK_DIR))
            for l in lines: yield f"data: {l}\n\n"
            yield "data: ✓ Containers and volumes removed.\n\n" if code == 0 \
                else "data: ⚠ compose down reported errors (continuing).\n\n"
        else:
            yield "data: → No running stack found — skipping compose down.\n\n"

        for vol in ("his_postgres_data",):
            r = subprocess.run(["docker", "volume", "rm", vol], capture_output=True, text=True)
            if r.returncode == 0:
                yield f"data: ✓ Removed volume {vol}.\n\n"

        yield "data: → Removing /share/his…\n\n"
        try:
            shutil.rmtree(str(HIS_DIR), ignore_errors=True)
            yield "data: ✓ /share/his removed.\n\n"
        except Exception as exc:
            yield f"data: ⚠ Could not remove /share/his: {exc}\n\n"

        yield "data: ✅ HIS fully uninstalled. You can now remove the add-on from HA.\n\n"
        yield "event: done\ndata: \n\n"
        READY_FLAG.unlink(missing_ok=True)
        pathlib.Path("/tmp/his_uninstalled").touch()

    return StreamingResponse(stream(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


# ── Wizard HTML ────────────────────────────────────────────────────────────────

_WIZARD_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HIS Setup</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>
  body{background:#0f172a}
  input[type=text],input[type=password]{background:#1e293b;border:1px solid #334155;color:#f1f5f9;border-radius:6px;padding:8px 12px;width:100%;font-size:.875rem}
  input:focus{outline:2px solid #6366f1;border-color:transparent}
  input:disabled{opacity:.4;cursor:not-allowed}
  select{background:#1e293b;border:1px solid #334155;color:#f1f5f9!important;border-radius:6px;padding:8px 12px!important;width:100%;font-size:.875rem;cursor:pointer;appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%2394a3b8' d='M6 8L1 3h10z'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 12px center;padding-right:36px!important}
  select:disabled{opacity:.4;cursor:not-allowed}
  select:focus{outline:2px solid #6366f1;border-color:transparent}
  label{color:#94a3b8;font-size:.8rem;font-weight:500;letter-spacing:.05em;text-transform:uppercase}
  .card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:24px}
  .section-title{color:#e2e8f0;font-size:1rem;font-weight:600}
  .hint{color:#64748b;font-size:.75rem;margin-top:4px}
  .hint a{color:#818cf8;text-decoration:underline}
  .btn-primary{background:#6366f1;color:white;border-radius:8px;padding:10px 24px;font-weight:600;cursor:pointer;border:none;transition:background .15s}
  .btn-primary:hover{background:#4f46e5}
  .btn-primary:disabled{background:#334155;color:#64748b;cursor:not-allowed}
  .btn-sm{border-radius:6px;padding:6px 14px;font-size:.8rem;font-weight:600;cursor:pointer;border:none;transition:background .15s;white-space:nowrap}
  .btn-action{background:#1e3a5f;color:#93c5fd;border:1px solid #2563eb;min-width:90px}
  .btn-action:hover:not(:disabled){background:#1e40af}
  .btn-action:disabled{opacity:.5;cursor:not-allowed}
  .btn-gen{background:#1e3a5f;color:#93c5fd;border:1px solid #2563eb}
  .btn-gen:hover{background:#1e40af}
  #log{background:#0a0a0a;color:#4ade80;font-family:monospace;font-size:.75rem;border-radius:8px;padding:16px;height:360px;overflow-y:auto;white-space:pre-wrap}
  .badge{display:inline-block;border-radius:4px;padding:2px 8px;font-size:.7rem;font-weight:600}
  .badge-req{background:#166534;color:#86efac}
  .badge-opt{background:#1e3a5f;color:#93c5fd}
  .badge-free{background:#14532d;color:#86efac}
  .badge-local{background:#1e3a5f;color:#7dd3fc}
  .badge-auto{background:#1e3a4a;color:#67e8f9}
  .domain-ok{color:#4ade80;font-size:.8rem}
  .domain-fail{color:#f87171;font-size:.8rem}
  .prov-list{border:1px solid #334155;border-radius:10px;overflow:hidden}
  .prov-item{border-bottom:1px solid #1e293b}
  .prov-item:last-child{border-bottom:none}
  .prov-item.validated .prov-row{border-left:3px solid #22c55e}
  .prov-item.errored .prov-row{border-left:3px solid #ef4444}
  .prov-item.is-primary .prov-row{border-left:3px solid #6366f1;background:#1a1a3e}
  .prov-row{display:flex;align-items:center;gap:10px;padding:13px 16px;cursor:pointer;background:#1e293b;transition:background .15s;border-left:3px solid transparent}
  .prov-row:hover{background:#243044}
  .prov-panel{display:none;padding:16px 20px 20px;background:#162032;border-top:1px solid #334155}
  .prov-panel.open{display:block}
  .prov-status{width:8px;height:8px;border-radius:50%;flex-shrink:0;background:#334155}
  .prov-status.ok{background:#22c55e}
  .prov-status.err{background:#ef4444}
  .prov-chevron{color:#64748b;font-size:.65rem;margin-left:auto;transition:transform .2s;flex-shrink:0}
  .prov-chevron.open{transform:rotate(180deg)}
  .prov-star{background:none;border:none;cursor:pointer;font-size:.95rem;opacity:.3;padding:0 4px;transition:opacity .15s;flex-shrink:0;line-height:1}
  .prov-star:hover{opacity:.7}
  .prov-star.active{opacity:1}
  .primary-chip{font-size:.6rem;background:#312e81;color:#a5b4fc;border-radius:3px;padding:1px 5px;font-weight:700;letter-spacing:.05em;flex-shrink:0}
  .validate-msg{font-size:.75rem;margin-top:5px;min-height:16px}
  .vmsg-ok{color:#4ade80}
  .vmsg-fail{color:#f87171}
  .vmsg-info{color:#94a3b8}
  .model-meta{font-size:.7rem;color:#64748b;margin-top:3px}
  .spinner{display:inline-block;width:12px;height:12px;border:2px solid #334155;border-top-color:#6366f1;border-radius:50%;animation:spin .7s linear infinite}
  @keyframes spin{to{transform:rotate(360deg)}}
  .repo-ok{border-color:#22c55e!important}
  .repo-fail{border-color:#ef4444!important}
</style>
</head>
<body class="min-h-screen p-6">
<div class="max-w-2xl mx-auto">
  <div class="mb-8 text-center">
    <div class="text-4xl mb-2">🏠</div>
    <h1 class="text-2xl font-bold text-white">HIS Setup</h1>
    <p class="text-slate-400 mt-1 text-sm">Household Intelligence System — first-run configuration</p>
  </div>

  <div id="form-view">

    <!-- ① Source Repository -->
    <div class="card mb-4">
      <div class="flex items-center gap-2 mb-3">
        <span class="section-title">HIS Repository</span>
        <span class="badge badge-req">Required</span>
      </div>
      <p class="text-slate-400 text-sm mb-4">The private HIS application repository to clone and run. <strong class="text-slate-300">Not</strong> this orchestrator repo.</p>
      <div class="space-y-4">
        <div>
          <label>Repository URL</label>
          <div class="flex gap-2 mt-1">
            <input type="text" id="repo_url" placeholder="https://github.com/you/his" autocomplete="off"
              oninput="onRepoInput()" class="flex-1 transition-all duration-200">
            <button class="btn-sm btn-action" id="repo-validate-btn" onclick="validateRepo()" disabled>Validate</button>
          </div>
          <div id="repo-vmsg" class="validate-msg"></div>
        </div>
        <div>
          <label>GitHub Token <span class="text-slate-500 normal-case font-normal">(for private repos)</span></label>
          <input type="password" id="repo_token" placeholder="ghp_…" autocomplete="off"
            oninput="onRepoInput()">
          <p class="hint">Fine-grained PAT with <strong>Contents: Read</strong> permission. Leave empty for public repos.</p>
        </div>
      </div>
    </div>

    <!-- ② AI Providers -->
    <div class="card mb-4">
      <div class="flex items-center gap-2 mb-1">
        <span class="section-title">AI Provider</span>
        <span class="badge badge-req">At least one required</span>
      </div>
      <p class="text-slate-400 text-sm mb-4">Expand a provider, enter your key and hit <strong class="text-slate-300">Validate</strong>. Click ⭐ to set as primary.</p>
      <div class="prov-list" id="prov-list"></div>
    </div>

    <!-- ③ Telegram -->
    <div class="card mb-4">
      <div class="flex items-center gap-2 mb-3">
        <span class="section-title">Telegram Bot</span>
        <span class="badge badge-opt">Optional</span>
      </div>
      <p class="text-slate-400 text-sm mb-4">Main interface for HIS. You can add this later.</p>
      <div class="space-y-4">
        <div>
          <label>Bot Token</label>
          <input type="password" id="telegram_bot_token" placeholder="123456:ABC…" autocomplete="off">
          <p class="hint">Create at <a href="https://t.me/BotFather" target="_blank">@BotFather</a> → /newbot</p>
        </div>
        <div>
          <label>Your Telegram User ID</label>
          <input type="text" id="telegram_allowed_user_ids" placeholder="123456789">
          <p class="hint">Ask <a href="https://t.me/userinfobot" target="_blank">@userinfobot</a> for your numeric ID.</p>
        </div>
      </div>
    </div>

    <!-- ④ Public URL -->
    <div class="card mb-4">
      <div class="flex items-center gap-2 mb-3">
        <span class="section-title">Public URL</span>
        <span class="badge badge-opt">Optional</span>
      </div>
      <p class="text-slate-400 text-sm mb-3">Required to receive Telegram messages. Usually your HA public URL.</p>
      <div>
        <label>Public Base URL</label>
        <div class="flex gap-2 mt-1">
          <input type="text" id="public_base_url" placeholder="https://ha.yourdomain.com" autocomplete="off">
          <button class="btn-sm btn-action" onclick="testDomain()">Test</button>
        </div>
        <p id="domain-status" class="mt-2 text-sm hidden"></p>
      </div>
    </div>

    <!-- ⑤ Home Assistant (auto-provisioned) -->
    <div class="card mb-4">
      <div class="flex items-center gap-2 mb-3">
        <span class="section-title">Home Assistant</span>
        <span class="badge badge-auto" id="ha-badge">⚡ Auto-configured</span>
      </div>
      <p class="text-slate-400 text-sm" id="ha-desc">HA URL and access token are automatically provided by the HA Supervisor.</p>
      <!-- Hidden token field — filled by prefill; shown as fallback if auto-provision fails -->
      <div id="ha-token-fallback" class="hidden mt-3">
        <label>Long-Lived Access Token</label>
        <input type="password" id="ha_token" placeholder="eyJ…" autocomplete="off">
        <p class="hint">HA → Profile → Security → Long-Lived Access Tokens → Create Token</p>
      </div>
      <input type="hidden" id="ha_token_hidden">
      <p class="hint mt-2">Override URL in Advanced settings if needed.</p>
    </div>

    <!-- ⑥ Advanced -->
    <div class="card mb-6">
      <details>
        <summary class="cursor-pointer text-slate-400 text-sm py-2 select-none hover:text-slate-300">▶ Advanced settings</summary>
        <div class="space-y-4 mt-4">
          <div><label>Home Assistant URL (override)</label><input type="text" id="ha_url" placeholder="http://homeassistant.local:8123"></div>
          <div>
            <label>HIS API Token</label>
            <div class="flex gap-2 mt-1">
              <input type="text" id="his_api_token" autocomplete="off">
              <button class="btn-sm btn-gen" onclick="gen('his_api_token',32)">↺ Gen</button>
            </div>
          </div>
          <div>
            <label>PostgreSQL Password</label>
            <div class="flex gap-2 mt-1">
              <input type="password" id="postgres_password" autocomplete="new-password">
              <button class="btn-sm btn-gen" onclick="gen('postgres_password',16)">↺ Gen</button>
            </div>
          </div>
        </div>
      </details>
    </div>

    <div id="error-msg" class="hidden mb-4 p-3 bg-red-900/40 border border-red-700 rounded-lg text-red-300 text-sm"></div>
    <button class="btn-primary w-full text-center" id="deploy-btn" onclick="configure()">🚀 Install HIS</button>

    <!-- Uninstall (shown when already configured) -->
    <div id="uninstall-section" class="hidden mt-8">
      <div class="card" style="border-color:rgba(127,29,29,.6)">
        <div class="flex items-center gap-2 mb-2"><span class="text-red-400 font-semibold">Danger Zone</span></div>
        <p class="text-slate-400 text-sm mb-4">Completely removes HIS — stops all containers, deletes the database, wipes <code class="text-slate-300">/share/his</code>. Cannot be undone.</p>
        <div id="uninstall-confirm" class="hidden mb-3 p-3 bg-red-900/30 border border-red-700 rounded-lg">
          <p class="text-red-300 text-sm font-semibold mb-2">Are you sure? All data will be permanently deleted.</p>
          <div class="flex gap-2">
            <button class="btn-sm btn-action" style="background:#7f1d1d;border-color:#ef4444;color:#fca5a5" onclick="startUninstall()">Yes, wipe everything</button>
            <button class="btn-sm btn-action" onclick="document.getElementById('uninstall-confirm').classList.add('hidden')">Cancel</button>
          </div>
        </div>
        <button class="btn-sm btn-action" style="border-color:#ef4444;color:#fca5a5"
          onclick="document.getElementById('uninstall-confirm').classList.remove('hidden')">🗑 Uninstall HIS</button>
      </div>
    </div>
  </div>

  <div id="deploy-view" class="hidden">
    <div class="card">
      <div class="section-title mb-4" id="deploy-title">Installing HIS…</div>
      <pre id="log"></pre>
      <div id="deploy-status" class="mt-4 text-sm text-slate-400"></div>
    </div>
  </div>
</div>

<script>
const API_BASE = window.location.pathname.replace(/\/+$/, '');
const PROVIDERS=[
  {id:'gemini',icon:'🟣',label:'Gemini',badge:'Free',badgeClass:'badge-free',
   desc:'Google — best-in-class embeddings, generous free tier.',
   keyPlaceholder:'AIza…',keyHint:'Free key at <a href="https://aistudio.google.com/app/apikey" target="_blank">aistudio.google.com</a>',
   defaultModel:'gemini-2.5-flash'},
  {id:'groq',icon:'🟡',label:'Groq',badge:'Free',badgeClass:'badge-free',
   desc:'Fastest inference — up to 14 400 req/day on free tier.',
   keyPlaceholder:'gsk_…',keyHint:'Free key at <a href="https://console.groq.com" target="_blank">console.groq.com</a>',
   defaultModel:'llama-3.3-70b-versatile'},
  {id:'openrouter',icon:'🔵',label:'OpenRouter',badge:'Free models',badgeClass:'badge-free',
   desc:'9+ free models incl. DeepSeek V4 Flash (1M context).',
   keyPlaceholder:'sk-or-…',keyHint:'Free key at <a href="https://openrouter.ai" target="_blank">openrouter.ai</a>',
   defaultModel:'deepseek/deepseek-v4-flash:free'},
  {id:'ollama',icon:'🟤',label:'Ollama',badge:'Local',badgeClass:'badge-local',
   desc:'Fully local — no data leaves your home.',isOllama:true,defaultModel:'llama3.2:3b'},
];
const ps={};
PROVIDERS.forEach(p=>{ps[p.id]={key:'',model:p.defaultModel,models:[],validated:false,open:false};});
let primaryProvider='groq';
let repoValidated=false;

function hexRand(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return Array.from(a).map(b=>b.toString(16).padStart(2,'0')).join('');}
function gen(id,n){const el=document.getElementById(id);if(el&&!el.disabled)el.value=hexRand(n);}
function val(id){return(document.getElementById(id)?.value||'').trim();}

// ── Repo validation ───────────────────────────────────────────────────────────
function onRepoInput(){
  const url=val('repo_url');
  const btn=document.getElementById('repo-validate-btn');
  btn.disabled=url.length<8;
  if(repoValidated){repoValidated=false;setRepoMsg('','');}
}

async function validateRepo(){
  const url=val('repo_url'),token=val('repo_token');
  const btn=document.getElementById('repo-validate-btn');
  btn.disabled=true;btn.innerHTML='<span class="spinner"></span>';
  setRepoMsg('⏳ Checking access…','vmsg-info');
  try{
    const r=await fetch(`${API_BASE}/validate-repo`,{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({url,token})});
    const d=await r.json();
    if(d.ok){
      repoValidated=true;
      setRepoMsg('✓ Repository accessible','vmsg-ok');
      document.getElementById('repo_url').classList.add('repo-ok');
      document.getElementById('repo_url').classList.remove('repo-fail');
    }else{
      repoValidated=false;
      setRepoMsg('✗ '+(d.error||d.message||'Access denied'),'vmsg-fail');
      document.getElementById('repo_url').classList.add('repo-fail');
      document.getElementById('repo_url').classList.remove('repo-ok');
    }
  }catch(e){setRepoMsg('✗ '+e.message,'vmsg-fail');}
  finally{btn.disabled=false;btn.textContent='Validate';}
}

function setRepoMsg(msg,cls){
  const el=document.getElementById('repo-vmsg');
  el.textContent=msg;el.className='validate-msg '+cls;
}

// ── Provider accordion ────────────────────────────────────────────────────────
function renderProviderList(){
  const list=document.getElementById('prov-list');
  const order=[...PROVIDERS].sort((a,b)=>a.id===primaryProvider?-1:b.id===primaryProvider?1:0);
  list.innerHTML=order.map(p=>{
    const s=ps[p.id],isPrim=p.id===primaryProvider;
    const itemCls=[s.validated?'validated':'',s.errored?'errored':'',isPrim?'is-primary':''].filter(Boolean).join(' ');
    return `<div class="prov-item ${itemCls}" id="item-${p.id}">
      <div class="prov-row" onclick="togglePanel('${p.id}')">
        <span class="prov-status ${s.validated?'ok':s.errored?'err':''}" id="dot-${p.id}"></span>
        <span class="text-lg leading-none">${p.icon}</span>
        <span class="text-slate-200 font-medium text-sm">${p.label}</span>
        <span class="badge ${p.badgeClass} text-xs">${p.badge}</span>
        ${isPrim?'<span class="primary-chip">PRIMARY</span>':''}
        <button class="prov-star ${isPrim?'active':''}" onclick="event.stopPropagation();setPrimary('${p.id}')">⭐</button>
        <span class="prov-chevron ${s.open?'open':''}" id="chev-${p.id}">▼</span>
      </div>
      <div class="prov-panel ${s.open?'open':''}" id="panel-${p.id}">
        <p class="text-slate-400 text-xs mb-4">${p.desc}</p>
        ${p.isOllama?renderOllamaPanel():renderKeyPanel(p)}
        <div id="model-section-${p.id}" class="${s.validated?'':'hidden'}">
          <label class="block mt-4 mb-1">Model</label>
          <select id="model-select-${p.id}" onchange="onModelChange('${p.id}')">
            <option value="${p.defaultModel}">${p.defaultModel}</option>
          </select>
          <div id="model-meta-${p.id}" class="model-meta"></div>
        </div>
      </div>
    </div>`;
  }).join('');
  PROVIDERS.forEach(p=>{
    if(ps[p.id].validated&&ps[p.id].models.length){
      renderModelSelect(p.id,ps[p.id].models,ps[p.id].model);
      document.getElementById('model-section-'+p.id)?.classList.remove('hidden');
    }
  });
}

function renderKeyPanel(p){
  return `<div><label>API Key</label>
    <div class="flex gap-2 mt-1">
      <input type="password" id="key-${p.id}" placeholder="${p.keyPlaceholder}" autocomplete="off"
        oninput="onKeyInput('${p.id}')" class="flex-1">
      <button class="btn-sm btn-action" id="validate-btn-${p.id}" onclick="validateProvider('${p.id}')" disabled>Validate</button>
    </div>
    <p class="hint">${p.keyHint}</p>
    <div id="vmsg-${p.id}" class="validate-msg"></div>
  </div>`;}

function renderOllamaPanel(){
  return `<div><label>Ollama URL</label>
    <div class="flex gap-2 mt-1">
      <input type="text" id="ollama_base_url" placeholder="http://192.168.1.x:11434" autocomplete="off"
        oninput="ps.ollama.validated=false;refreshItemState('ollama')" class="flex-1">
      <button class="btn-sm btn-action" id="validate-btn-ollama" onclick="validateProvider('ollama')">Connect</button>
    </div>
    <div id="vmsg-ollama" class="validate-msg"></div>
  </div>`;}

function togglePanel(id){
  ps[id].open=!ps[id].open;renderProviderList();
  PROVIDERS.forEach(p=>{if(!p.isOllama){const el=document.getElementById('key-'+p.id);if(el&&ps[p.id].key)el.value=ps[p.id].key;}});
}
function setPrimary(id){primaryProvider=id;renderProviderList();
  PROVIDERS.forEach(p=>{if(!p.isOllama){const el=document.getElementById('key-'+p.id);if(el&&ps[p.id].key)el.value=ps[p.id].key;}});}
function onKeyInput(provider){
  const key=(document.getElementById('key-'+provider)?.value||'').trim();
  ps[provider].key=key;
  const btn=document.getElementById('validate-btn-'+provider);
  if(btn)btn.disabled=key.length<8;
  if(ps[provider].validated){ps[provider].validated=false;ps[provider].errored=false;refreshItemState(provider);}
}
function refreshItemState(id){
  const item=document.getElementById('item-'+id);if(!item)return;
  item.className=['prov-item',ps[id].validated?'validated':'',ps[id].errored?'errored':'',id===primaryProvider?'is-primary':''].filter(Boolean).join(' ');
  const dot=document.getElementById('dot-'+id);
  if(dot)dot.className='prov-status '+(ps[id].validated?'ok':ps[id].errored?'err':'');
}

async function validateProvider(provider){
  const p=PROVIDERS.find(x=>x.id===provider);
  const btn=document.getElementById('validate-btn-'+provider);
  const key=p.isOllama?(val('ollama_base_url')||'http://ollama:11434'):((document.getElementById('key-'+provider)?.value||ps[provider].key||'').trim());
  if(!p.isOllama&&key.length<8)return;
  if(btn){btn.disabled=true;btn.innerHTML='<span class="spinner"></span>';}
  setVmsg(provider,'⏳ Connecting…','vmsg-info');
  try{
    const resp=await fetch(`${API_BASE}/providers/${provider}/models?api_key=${encodeURIComponent(key)}`);
    const data=await resp.json();
    if(!resp.ok)throw new Error(data.detail||`HTTP ${resp.status}`);
    const models=data.models||[];
    ps[provider].models=models;ps[provider].validated=true;ps[provider].errored=false;
    if(!p.isOllama)ps[provider].key=key;
    setVmsg(provider,`✓ ${models.length} models available`,'vmsg-ok');
    refreshItemState(provider);
    renderModelSelect(provider,models,ps[provider].model);
    document.getElementById('model-section-'+provider)?.classList.remove('hidden');
  }catch(err){
    ps[provider].validated=false;ps[provider].errored=true;
    setVmsg(provider,'✗ '+err.message,'vmsg-fail');refreshItemState(provider);
  }finally{if(btn){btn.disabled=false;btn.textContent=p.isOllama?'Connect':'Validate';}}
}

function setVmsg(id,msg,cls){const el=document.getElementById('vmsg-'+id);if(el){el.textContent=msg;el.className='validate-msg '+cls;}}
function onModelChange(provider){ps[provider].model=document.getElementById('model-select-'+provider)?.value||'';}
function renderModelSelect(provider,models,current){
  const sel=document.getElementById('model-select-'+provider);if(!sel)return;
  const rec=models.filter(m=>m.recommended),rest=models.filter(m=>!m.recommended);
  sel.innerHTML='';
  function makeOpt(m){const o=document.createElement('option');o.value=m.id;let l=m.name||m.id;if(m.context_length)l+=` · ${(m.context_length/1000).toFixed(0)}k`;if(m.recommended)l+=' ⭐';o.textContent=l;o.selected=m.id===current;return o;}
  if(rec.length&&rest.length){const rg=document.createElement('optgroup');rg.label='⭐ Recommended';rec.forEach(m=>rg.appendChild(makeOpt(m)));sel.appendChild(rg);const og=document.createElement('optgroup');og.label='All models';rest.forEach(m=>og.appendChild(makeOpt(m)));sel.appendChild(og);}
  else models.forEach(m=>sel.appendChild(makeOpt(m)));
  if(!sel.value&&models.length)sel.value=models[0].id;
}

// ── Domain test ───────────────────────────────────────────────────────────────
async function testDomain(){
  const url=val('public_base_url');if(!url){showDomainStatus('Enter a URL first.',false);return;}
  try{
    const r=await fetch(`${API_BASE}/validate-domain`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});
    const d=await r.json();
    showDomainStatus(d.ok?'✓ Reachable'+(d.note?' — '+d.note:''):'✗ '+(d.error||'Not reachable'),d.ok);
  }catch(e){showDomainStatus('✗ '+e.message,false);}
}
function showDomainStatus(msg,ok){
  const el=document.getElementById('domain-status');
  el.textContent=msg;el.className='mt-2 text-sm '+(ok?'domain-ok':'domain-fail');el.classList.remove('hidden');
}

// ── Configure + deploy ────────────────────────────────────────────────────────
function showError(msg){document.getElementById('error-msg').textContent=msg;document.getElementById('error-msg').classList.remove('hidden');}
function clearError(){document.getElementById('error-msg').classList.add('hidden');}

function configure(){
  clearError();
  if(!val('repo_url')){showError('Repository URL is required.');return;}
  if(!repoValidated){showError('Please validate the repository first.');return;}
  const hasAny=ps.gemini.validated||ps.groq.validated||ps.openrouter.validated||ps.ollama.validated;
  if(!hasAny){showError('At least one AI provider must be validated.');return;}
  let eff=primaryProvider;
  if(!ps[eff].validated)eff=PROVIDERS.find(p=>ps[p.id].validated)?.id||eff;
  const fields={
    repo_url:val('repo_url'),repo_token:val('repo_token'),
    llm_primary_provider:eff,
    embedding_provider:ps.gemini.validated?'gemini':(ps.ollama.validated?'ollama':eff),
    gemini_api_key:ps.gemini.key||'',gemini_model:ps.gemini.model,
    groq_api_key:ps.groq.key||'',groq_model:ps.groq.model,
    openrouter_api_key:ps.openrouter.key||'',openrouter_model:ps.openrouter.model,
    ollama_base_url:val('ollama_base_url')||'http://ollama:11434',ollama_model:ps.ollama.model,
    ha_url:val('ha_url')||'__from_prefill__',
    ha_token:val('ha_token')||val('ha_token_hidden')||'__from_prefill__',
    public_base_url:val('public_base_url'),
    his_api_token:val('his_api_token'),
    postgres_password:val('postgres_password'),
    telegram_bot_token:val('telegram_bot_token'),
    telegram_webhook_secret:hexRand(16),
    telegram_allowed_user_ids:formatIds(val('telegram_allowed_user_ids')),
  };
  const btn=document.getElementById('deploy-btn');btn.disabled=true;btn.textContent='Saving…';
  fetch(`${API_BASE}/configure`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fields)})
    .then(r=>r.json()).then(d=>{
      if(d.ok)startDeploy();
      else{showError(d.error||'Failed.');btn.disabled=false;btn.textContent='🚀 Install HIS';}
    }).catch(e=>{showError('Network error: '+e.message);btn.disabled=false;btn.textContent='🚀 Install HIS';});
}

function formatIds(raw){if(!raw)return'[]';raw=raw.replace(/[\[\]]/g,'');return'['+raw.split(/[\s,]+/).filter(Boolean).join(',')+']';}

function startDeploy(isUninstall=false){
  document.getElementById('form-view').classList.add('hidden');
  document.getElementById('deploy-view').classList.remove('hidden');
  document.getElementById('deploy-title').textContent=isUninstall?'Uninstalling HIS…':'Installing HIS…';
  const log=document.getElementById('log'),status=document.getElementById('deploy-status');
  log.textContent='';
  const es=new EventSource(`${API_BASE}/${isUninstall?'uninstall':'deploy'}`);
  es.onmessage=e=>{log.textContent+=e.data+'\n';log.scrollTop=log.scrollHeight;};
  es.addEventListener('done',()=>{
    es.close();
    status.innerHTML=isUninstall
      ?`<div class="text-green-400 font-semibold">✅ Uninstall complete.</div><p class="text-slate-400 text-sm mt-2">You can now remove the add-on from HA Settings → Add-ons.</p>`
      :`<div class="text-green-400 font-semibold mb-3">✅ HIS installed!</div><p class="text-slate-400 text-sm">Reloading in 5 seconds…</p>`;
    if(!isUninstall)setTimeout(()=>location.reload(),5000);
  });
  es.addEventListener('error',()=>{es.close();status.textContent=`❌ ${isUninstall?'Uninstall':'Install'} failed — check the log.`;status.className='mt-4 text-sm text-red-400';});
}

function startUninstall(){
  document.getElementById('uninstall-confirm').classList.add('hidden');
  startDeploy(true);
}

// ── Init ──────────────────────────────────────────────────────────────────────
window.addEventListener('DOMContentLoaded',()=>{
  renderProviderList();
  setTimeout(()=>{
    if(!val('his_api_token'))document.getElementById('his_api_token').value=hexRand(32);
    if(!val('postgres_password'))document.getElementById('postgres_password').value=hexRand(16);
  },120);
  fetch(`${API_BASE}/prefill`).then(r=>r.json()).then(data=>{
    if(data.GEMINI_API_KEY)ps.gemini.key=data.GEMINI_API_KEY;
    if(data.GROQ_API_KEY)ps.groq.key=data.GROQ_API_KEY;
    if(data.OPENROUTER_API_KEY)ps.openrouter.key=data.OPENROUTER_API_KEY;
    if(data.LLM_PRIMARY_PROVIDER)primaryProvider=data.LLM_PRIMARY_PROVIDER;
    renderProviderList();
    PROVIDERS.forEach(p=>{if(!p.isOllama){const el=document.getElementById('key-'+p.id);if(el&&ps[p.id].key){el.value=ps[p.id].key;onKeyInput(p.id);}}});
    const km={HA_URL:'ha_url',TELEGRAM_BOT_TOKEN:'telegram_bot_token',
      TELEGRAM_ALLOWED_USER_IDS:'telegram_allowed_user_ids',HIS_API_TOKEN:'his_api_token',
      PUBLIC_BASE_URL:'public_base_url',POSTGRES_PASSWORD:'postgres_password',
      OLLAMA_BASE_URL:'ollama_base_url'};
    for(const[k,field]of Object.entries(km)){if(data[k]){const el=document.getElementById(field);if(el)el.value=data[k];}}
    // HA token — store in hidden field; show manual input if auto-provision failed
    if(data.HA_TOKEN){
      document.getElementById('ha_token_hidden').value=data.HA_TOKEN;
    } else {
      document.getElementById('ha-badge').textContent='⚠ Manual required';
      document.getElementById('ha-badge').className='badge badge-req';
      document.getElementById('ha-desc').textContent='Could not auto-provision HA token. Please enter one manually.';
      document.getElementById('ha-token-fallback').classList.remove('hidden');
    }
    // Prefill repo fields
    if(data.REPO_URL){
      document.getElementById('repo_url').value=data.REPO_URL;
      document.getElementById('repo-validate-btn').disabled=false;
    }
    if(data.REPO_TOKEN)document.getElementById('repo_token').value=data.REPO_TOKEN;
    // Auto-validate providers with prefilled keys
    const toValidate=PROVIDERS.filter(p=>p.isOllama?data.OLLAMA_BASE_URL:ps[p.id].key);
    toValidate.forEach((p,i)=>setTimeout(()=>validateProvider(p.id),i*600));
    // Show uninstall section and update button if already configured
    if(data.HA_TOKEN){
      document.getElementById('uninstall-section').classList.remove('hidden');
      document.getElementById('deploy-btn').textContent='💾 Save & Restart HIS';
    }
    // Auto-validate repo if prefilled
    if(data.REPO_URL)setTimeout(()=>validateRepo(),300);
  }).catch(()=>{});
});
</script>
</body>
</html>"""


@app.get("/", response_class=HTMLResponse)
@app.get("", response_class=HTMLResponse)
async def wizard_ui():
    return HTMLResponse(_WIZARD_HTML)
